app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

home:
    path:     /
    defaults: { _controller: "AppBundle:Default:index" }
    methods:  GET
club_presentation:
    path:     /club
    defaults: { _controller: "AppBundle:Club:Presentation" }
    methods:  GET
Admin:
    path:     /admin
    defaults: { _controller: "AppBundle:Event:Index" }
    methods:  GET
# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
app_event:
        resource: "@AppBundle/Resources/config/routing/event.yml"
        prefix:   /event

arbia:
    resource: "@ArbiaBundle/Resources/config/routing.yml"
    prefix:   /arbia

ecole:
    resource: "@EcoleBundle/Controller/"
    type:     annotation
    prefix:   /enfant/aziz

gestion_cantine:
    resource: "@GestionCantineBundle/Controller/"
    type:     annotation
    prefix:   /Malek
